version: "3.8"
services:
  main:
    build: .
    image: mybot:latest
    container_name: ColorStackBot
    environment:
      - DISCORD_TOKEN 
      - CHANNEL_ID
      - GIT_TOKEN
    volumes:
      - ./commits:/app/commits