version: "3.8"
services:
  main:
    build: .
    image: mybot:latest
    container_name: ColorStackBot
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CHANNEL_ID: ${CHANNEL_ID}
      GIT_TOKEN: ${GIT_TOKEN}
    volumes:
      - ./commits:/app/commits
      - ./logs:/app/logs
  redis:
    image: redis:latest
    container_name: Redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379

volumes:
  redis_volume_data:
