version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - redis 

  main:
    build: .
    image: mybot:latest
    container_name: ColorStackBot
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GIT_TOKEN: ${GIT_TOKEN}
    volumes:
      - ./commits:/app/commits
      - ./logs:/app/logs
    depends_on:
      - redis  

  redis:
    image: redis:latest
    container_name: Redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - "127.0.0.1:6379:6379" 

volumes:
  redis_volume_data:
