name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - main
      - test

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          if ! command -v docker-compose &> /dev/null; then
            echo "docker-compose could not be found, installing..."
            apt-get update && sudo apt-get install -y docker-compose
          else
            echo "docker-compose is already installed."
          fi

      - name: Build Docker Image
        run: docker-compose build

      - name: Run Tests
        run: docker-compose run --rm main pytest /app/tests

      - name: Shutdown Docker Containers
        run: docker-compose down

      - name: Cleanup Unused Docker Images
        run: docker image prune -f
