name: Deploy to Oracle Cloud VM

on:
  push:
    branches:
      - main
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          if ! command -v docker-compose &> /dev/null; then
            echo "docker-compose could not be found, installing..."
            sudo apt-get update && sudo apt-get install -y docker-compose
          else
            echo "docker-compose is already installed."
          fi

      - name: Docker Build
        run: sudo docker-compose build

      - name: Run Tests
        run: sudo docker-compose run --rm main pytest /app/tests

      - name: Shutdown Docker Containers
        run: sudo docker-compose down
      
      - name: Cleanup Unused Images
        run: sudo docker image prune -f

      - name: SSH into Oracle VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}          
          script: |
            cd ColorStack-Discord-Bot/
            echo "Signed into VM"
            git pull
            sudo docker-compose down
            sudo docker-compose up -d --build
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}